### ISSUE TITLE
Missing Ed25519 to Curve25519 key conversion

### ISSUE THREAD

**Issue by istankovic** [dnaq/sodiumoxide#85] opened 2015-09-02 20:17 UTC
It would be nice to have bindings for these:
```
crypto_sign_ed25519_pk_to_curve25519
crypto_sign_ed25519_sk_to_curve25519
```

**Comment by dnaq** [comment] 2015-09-03 13:35
I've been holding off adding these functions since using the same key for different purposes carries the risk of opening you up to cross protocol attacks unless you're really careful. I might add them, but with a scary warning in the documentation, but I'd prefer not to to be honest.

What is your use case?

**Comment by istankovic** [comment] 2015-09-03 18:11
While I basically agree, I have to point out that if one is not careful with nonces,
one may very well end up with a broken system (even more easily, I'd say, than by
reusing the same key for signing and encryption).  And as far as I can see, sodiumoxide
does have bindings for functions taking nonces...

**Comment by dnaq** [comment] 2015-09-04 07:30
I fully agree.The problem is that (with the primitives in NaCl) nonces are a necessity for creating a working cryptosystem. Reusing the same key can usually be avoided (e.g. by using key derivation from a master key).

There are misuse-resistance block cipher modes, where nonce-reuse isn't that big of a problem, e.g. SIV-mode, but NaCl doesn't expose any misuse-resistant primitives.

That being said I will probably add the bindings to the two functions you requested, but with a suitable warning. I'm still interested in your use case though.

**Comment by eminence** [comment] 2015-10-20 02:43
I think my use-case is just easy-of-use.  Sometimes I want to encrypt data, other times I just want to sign it (since I believe working with signatures is faster than encrypting).    Tt would be nice for the receiving end to have to manage only 1 public key, not two

**Comment by dnaq** [comment] 2015-10-20 13:30
Signatures aren't much faster than encryption (both `crypto::box_::seal()` and `crypto::sign::sign()` do one curve multiplication). However they are for completely different use-cases. e.g. `crypto::box_` uses public key authenticators and does not give you non-repudiation whereas `crypto::sign` gives you non-repudiation.

I'm going to close this issue for now since I haven't seen a security proof that says that cross protocol attacks are impossible when using the same key for both curve25519 and ed25519.

**Closed by dnaq** 2015-10-20 13:30 UTC
Labels: enhancement

**Comment by eminence** [comment] 2015-10-20 14:19
To play devil's advocate: if libsodium provides this function, should it also be exposed by the bindings?   It could come with a similar warning for scalarmut and friends:

> Unless you know what you're doing you most certainly don't want to use the functions in `crypto::scalarmult`, `crypto::stream`, `crypto::auth` and `crypto::onetimeauth`.


(For the record, I am fairly well persuaded by the argument "This might hurt you, you should not do this", especially in the world of crypto.  I similar argument might be "Don't be lazy, you should use the correct primitive for your usecase")

**Comment by zmanian** [comment] 2016-08-29 16:36
The Signal protocol uses Curve25519 -> Ed25519 conversion to sign the ephemeral keys. Just wanted to mention the use case.

Just wanted to mention the use case.

**Comment by dominictarr** [comment] 2016-08-30 06:57
libsodium wouldn't have added this function if it was insecure, they discuss adding this
in https://github.com/jedisct1/libsodium/issues/77
this comment https://github.com/jedisct1/libsodium/issues/77#issuecomment-90818356 links to a paper and discussion about how it is secure to have dual use eliptic curve keys. This would not be secure with RSA,  but ed25519/curve25519 is a different thing

**Comment by dnaq** [comment] 2016-08-30 08:59
The paper proves the security of ECDSA +ECIES and EC-Schnorr+ECIES. These
aren't the cryptographic primitives that are used, so that proof isn't
valid. The paper also shows some combinations where the security falls
apart completely.

That being said, I'm not arguing that it's insecure, I'm arguing that it
isn't proven secure.

**Comment by Luke-Nukem** [comment] 2018-03-09 03:42
The one and only reason I can think of for requiring this, is easier key management. That is, not having to juggle two public keys.

**Comment by the-kenny** [comment] 2019-01-10 14:51
Another protocol using this conversion is the "Secret Handshare Protocol" ([Paper](https://ssbc.github.io/docs/shs.pdf)) used by SecureScuttlebutt ([Protocol](https://ssbc.github.io/scuttlebutt-protocol-guide/)).

**Comment by dominictarr** [comment] 2019-01-11 03:37
most cryptography we use isn't _proven secure_, it's only _believed_ to be secure, given that lots of smart people have looked and they have not found problems.
there isn't any proof that [one way functions actually exist](https://en.wikipedia.org/wiki/One-way_function) but without that we don't have hash functions, etc.

**Comment by adria0** [comment] 2020-01-08 14:39
@dnaq, sorry for insist to this already-closed feature request, but there's any way that this function will be available eventually? We are implementing the secure scuttlebut protocol in https://github.com/Kuska-ssb/kuska-handshake and we just need this key conversion.

What about having a new crate feature to allow this extra functionality?
